### ISSUE TITLE
Question about "etcd" snapshot provider

### ISSUE THREAD

**Issue by tamalsaha** [Quentin-M/etcd-cloud-operator#12]
Hi,
Is there a reason for implicit import of https://github.com/Quentin-M/etcd-cloud-operator/blob/master/pkg/etcd/server.go#L34 ?

Thanks.

**Comment by Quentin-M** [comment]
Hi there,

Yes, this is what will make the go runtime execute the [init](https://github.com/Quentin-M/etcd-cloud-operator/blob/775322b476534265a80aa883cafbe85e8e736c25/pkg/providers/snapshot/etcd/etcd.go#L32) function of the package, which registers the provider.

This specific provider has a special purpose, and does not actually represent a fully implemented snapshot backend. It is only used by the operator to attempt a restore from local data rather than uploaded data if the local data is more recent, which may be the case if a quorum of instances was killed suddenly (e.g sigkill, power loss), and any of them restart with their local data store (e.g. EBS volume).

**Comment by tamalsaha** [comment]
Thanks @Quentin-M .
