### ISSUE TITLE
Backup and restore support

### ISSUE THREAD

**Issue by iamnst19** [Quentin-M/etcd-cloud-operator#78]
Is there a support for backup and restore for this operator. I can see the backup is supported but don't seem to see restore

**Comment by Quentin-M** [comment]
Hey @iamnst19,

You are right, the operator will ensure that snapshots make their way into S3 on a regular basis. In terms of restore, the recovery is completely automated when nodes come up and attempt to either bootstrap (called "seed" in this project) the cluster or join the existing healthy one.

The relevant state machine steps are [here](https://github.com/Quentin-M/etcd-cloud-operator/blob/32a874136c47d30babb84a2956b5e960c619ab33/pkg/operator/operator.go#L180-L200). The operators will first [determine](https://github.com/Quentin-M/etcd-cloud-operator/blob/32a874136c47d30babb84a2956b5e960c619ab33/pkg/operator/operator.go#L135) the status of the cluster, its members and the latest datastore revision available to each of the members (either as seen locally on their disk, or as seen in the S3 backup they have access to) - and then either join the existing cluster if healthy, or otherwise let the node who has the most recent datastore revision seed a new cluster which the others will be able to join shortly thereafter. For instance, if none of the nodes have any data locally, then they'd all see the same latest backup revision from S3 and the seeder will be the first instance when sorted alphanumerically; Or one of the members has a more recent datastore on disk than the one available in S3 - then that member will be seeding a new cluster for the others to join.

So while recovery from backup during disasters is automated, it's also relatively trivial to force a cluster to come with a very specific backup you might have on hand - it simply has to be the latest backup in S3 or on the disk of one of the members, when the etcd cluster is down & the operator is starting up.

**Comment by iamnst19** [comment]
is the backup and restore kms encrypted for s3?

**Comment by iamnst19** [comment]
And any requirement to pass the kms key alias as environment variable to the code?

**Comment by Quentin-M** [comment]
Nope - The list of default Terraform variables is [here](https://github.com/Quentin-M/etcd-cloud-operator/tree/master/terraform/platforms/aws) and the operator's default configuration file is [here](https://github.com/Quentin-M/etcd-cloud-operator/blob/master/config.example.yaml).

**Comment by iamnst19** [comment]
I had used the S3 aws server side encryption and not the kms and created a policy attached to the role and use the role with the serviceaccount of etcd thus creating a trust relation. The S3 bucket was created manually and the bucket name was added to the snapshot. Restore did not work for me. Is it mandatory to create the s3 bucket and policy through the default provider to work as expected?

**Comment by Quentin-M** [comment]
No, not necessarily - as long as ECO can read/write from the S3 bucket, it should be fine. Are the snapshots being written to S3? If so, that's a good first step and so we'd have to look at the logs to understand why your recovery didn't happen as expected.

**Comment by iamnst19** [comment]
thanks
